name: QA Workflow
run-name: ${{ github.actor }} is learning GitHub Actions
on: [workflow_dispatch]
env:
  SF_USER_ENV: sfuser_env
jobs:
  Deploy-QA-Branch-To-UAT:
    runs-on: ubuntu-latest
    steps:
      - name: SF User 1 var
        run: echo "$SF_USER"
      - name: SF User ENV
        run: echo $SF_USER_ENV
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Salesforce CLI
        run: npm install -g bats
      - name: Run deployment job
        run: bats -v
